spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
logging:
  level:
    com.hellozjf.study.jpa: debug